# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: default

replicaCount: 1

imagePullSecrets:
  enabled: false
  name: ecrsecret

image:
  registry:
  repository: postgres
  tags: 11.7
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5432

postgres_root_password: mstr123
postgres_user: postgres
postgres_password: mstr123

volumes:
  enabled: false
  project: project name of the reposotory
  capacity: the space that needs to be required
  nfs_server: provide your nfs server ip
  mount_path: mount source folder path on nfs server
  db_usage: the usage of this pv
  storage_class: storage class name

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
