export default {
    GENERAL: 'general',
    ALL: 'all',
    //PAGE
    PAGE_TAB1: '1',
    PAGE_TAB2: '2',
    //alert
    DELETE: 'Delete',
    SHARE: 'Share',
    //info
    NAME: 'name',
    DESC: 'desc',
    //Home Screen
    MODE_USE_DEFAULT_HOME_SCREEN: 0,
    MODE_USE_DOSSIER_AS_HOME_SCREEN: 1,
    REVIEW_MODE_TABLET: 'tablet',
    REVIEW_MODE_PHONE: 'Phone',
    HOME_SCREEN: 'homeScreen',
    HOME_DOCUMENT: 'homeDocument',
    HOME_LIBRARY: 'homeLibrary',
    MODE: 'mode',
    URL: 'url',
    ICONS: 'icons',
    TOOLBAR_MODE: 'toolbarMode',
    //Advanced Settings
    AUTH_MODES: 'authModes',
    DISABLE_ADVANCED_SETTINGS: 'disableAdvancedSettings',
    DISABLE_PREFERENCES: 'disablePreferences',
    UPDATE_INTERVAL: 'updateInterval',
    UPDATE_INTERVAL_TEXT: 'updateIntervalText',
    NETWORK_TIMEOUT: 'networkTimeout',
    LOG_LEVEL: 'logLevel',
    MAX_LOG_SIZE: 'maxLogSize',
    CACHE_CLEAR_MODE: 'cacheClearMode',
    CLEAR_CACHE_ON_LOGOUT: 'clearCacheOnLogout',
    CLEAR_CACHE_ON_CLOSE: 'clearCacheOnClose',
    //Config Constants
    DEFAULT_NETWORK_TIMEOUT: 180,
    UPDATE_INTERVAL_DISABLED: -1,
    DEFAULT_MAX_LOG_SIZE: 500,
    LOG_LEVEL_ALL: 0,
    LOG_LEVEL_INFO: 10,
    LOG_LEVEL_WARNING: 12,
    LOG_LEVEL_SEVERE: 14,
    LOG_LEVEL_OFF: 16,
    CLEAR_ON_CLOSE: 2,
    CLEAR_AUTOMATIC: 1,

    // components 
    SHOW_TOOLBAR: 0,
    COLLAPSE_TOOLBAR: 1,

    // icons
    ICON_SIDEBAR: 'sidebars',
    ICON_SORT_FILTER: 'sortAndFilter',
    ICON_MULTI_SELECT: 'multiSelect',
    ICON_SEARCH: 'search',
    ICON_COMMENTS: 'comments',
    ICON_NOTIFICATIONS: 'notifications',
    ICON_OPTIONS: 'options',
    ICON_TOCS: 'TOCs',
    ICON_BOOKMARK: 'bookmark',
    ICON_RESET: 'reset',
    ICON_FILTER: 'filter',
    ICON_SHARE: 'share',
    ICON_DATA_SEARCH: 'dataSearch',
    ICON_HYPER: 'hyper',
    ICON_AA_FONT: 'aaFont',
    ICON_ALL: 'all',
    ICON_FAV: 'favourites',
    ICON_RECENENT: 'recents',
    ICON_DEFAULT_GROUP: 'defaultGroups',
    ICON_MY_GROUP: 'myGroups'
}