{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
{{- include "namespace" . | indent 2 }}
  labels:
{{- include "product.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- include "ingress_host" . | indent 2 }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-{{ .Release.Name }}
          servicePort: {{ .Values.service.port }}
{{- end }}
