Vagrant::Project.configure(:virtualbox) do |env|
  TKN-.-snake_case_project_name-.-TKN_centos :TKN-.-snake_case_project_name-.-TKN_centos do

    provider{
      network{
        ip_address "10.62.78.100"
      }
      memory '480'
    }
  
  end
end
