apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
{{- include "namespace" . | indent 2 }}
  labels:
{{- include "product.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{- include "product.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - /opt/mstr/modelservice/bin/start.sh
        livenessProbe:
          httpGet:
            path: /model/application/health
            port: 9500
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /model/application/health
            port: 9500
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 9500
{{- if .Values.config.from_config_map }}
        volumeMounts:
        - name: config-volume
          mountPath: /opt/mstr/modelservice/admin/modelservice.conf
          subPath: modelservice.conf
{{- end }}
        resources: {}

{{- if .Values.config.from_config_map }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ tpl .Values.config.config_map_name . }}
          items:
          - key: modelservice.conf
            path: modelservice.conf
{{- end }}
      restartPolicy: Always
status: {}
