# Default values for library.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: default
  branch_name: next

replicaCount: 1

imagePullSecrets:
  enabled: false
  name: ecrsecret

image:
  repository: 899557540756.dkr.ecr.us-east-1.amazonaws.com/iserver
  version: latest
  pullPolicy: IfNotPresent

odbc:
  db_md_name: Tutorial
  db_wh_name: Tutorial
  dsn_md: poc_metadata
  dsn_wh: tutorial_wh

config:
  from_config_map: false
  config_map_name: default-configmap-{{ .Release.Name }}

dbserver:
  override: false
  md_server: provide your md server
  wh_server: provide your wh server

service:
  type: ClusterIP
  port: 34952
rest:
  type: ClusterIP
  port: 34962
config:
  is_config_file: https://s3.amazonaws.com/yaou-demo/Tutorial/iserver-config-tutorial.zip

resources:
  requests:
    memory: 2Gi
  limits:
    memory: 8Gi

streamer:
  enabled: false

ingress:
  enabled: false
  host: please_define

volumes:
  cube:
    enabled: false
    nfs_server: provide your nfs server ip
    mount_path: mount source folder path on nfs server
    project_id: project id of cube backup
    mount_to: mount target path in container
