---
global:
  namespace: ci
  branch_name: m2021

postgres-md:
  replicaCount: 1
  image:
    registry:
    repository: postgres
    tags: 11.7
    pullPolicy: IfNotPresent
  database_url: https://nexus.internal.microstrategy.com/repository/DBBackup/com/microstrategy/DBBackup/PSQL11/homescreenadmin/11.3.003/homescreenadmin-11.3.003.zip
  database_name: poc_metadata
  postgres_password: mstr1234
  postgres_user: postgres
  service:
    type: ClusterIP
  config:
    from_config_map: true
    config_map_name: configmap-{{ .Release.Name }}

iserver:
  replicaCount: 1
  image:
    repository: nexus.internal.microstrategy.com:49080/iserver
    version: m2021-.-latest
    pullPolicy: IfNotPresent
  config:
    from_config_map: true
    config_map_name: configmap-{{ .Release.Name }}
    serverdef: mtdi
  odbc:
    db_md_name: poc_metadata
    dsn_md: poc_metadata
    db_md_user: postgres
    md_type: postgresql
  dbserver:
    override: true
    md_server: postgres-md-{{ .Release.Name }}
  service:
    type: ClusterIP
    port: 34952
  connectivity:
    login: 
    password: 
    projectName: 
  ingress:
    enabled: false
    host: iserver-m2021-dev.internal.microstrategy.com

library:
  replicaCount: 1
  image:
    repository: nexus.internal.microstrategy.com:49080/web-dossier
    version: m2021-.-latest
    pullPolicy: Always
  service:
    type: ClusterIP
  config:
    from_config_map: true
    config_map_name: configmap-{{ .Release.Name }}
  ingress:
    enabled: true
    host: library-web-dossier-m2021-dev.internal.microstrategy.com
