apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
{{- include "namespace" . | indent 2 }}
  labels:
{{- include "product.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{- include "product.labels" . | indent 8 }}
    spec:
{{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 3306
{{- if .Values.config.from_config_map }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
{{- end }}
        env:
        - name: MYSQL_USER
          value: {{ .Values.mysql_user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql_password }}
        - name: DATABASE_URL
          value: {{ .Values.database_url }}
        - name: MYSQL_USER
          value: {{ .Values.mysql_user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql_password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database_name }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql_root_password }}
      restartPolicy: Always
      resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- if .Values.config.from_config_map }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ tpl .Values.config.config_map_name . }}
          items:
          - key: my.cnf
            path: my.cnf
{{- end }}
