# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: iserver-configmap-{{ .Release.Name }}
#   # labels:
#   #   release: {{ .Release.Name }}
# data:
#   odbc.ini: |-
#     [ODBC Data Sources]
#     {{ .Values.odbc.dsn_wh }}=MySQL ODBC 5.x Driver
#     {{ .Values.odbc.dsn_md }}=MySQL ODBC 5.x Driver
#
#     [ODBC]
#     Trace=0
#     TraceFile=odbctrace.out
#     TraceDll=/iserver-install/BIN/Linux/lib/MYtrcXX.so
#     InstallDir=/iserver-install/BIN/Linux/odbc
#     IANAAppCodePage=106
#     UseCursorLib=0
#     UNICODE=UTF-8
#
#     [{{ .Values.odbc.dsn_md }}]
#     DriverUnicodeType=1
#     Description=MySQL ODBC 5.x Driver
#     PORT=3306
#     DATABASE={{ .Values.odbc.db_md_name }}
#     CHARSET=utf8
# {{- if .Values.dbserver.override }}
#     SERVER={{ .Values.dbserver.md_server }}
# {{- else }}
#     SERVER=mysql-{{ .Release.Name }}
# {{- end }}
#     OPTION=2
#     SOCKET=#
#     Driver=/usr/lib64/libmyodbc5w.so
#
#     [{{ .Values.odbc.dsn_wh }}]
#     DriverUnicodeType=1
#     Description=MySQL ODBC 5.x Driver
#     PORT=3306
#     DATABASE={{ .Values.odbc.db_wh_name }}
#     CHARSET=utf8
# {{- if .Values.dbserver.override }}
#     SERVER={{ .Values.dbserver.wh_server }}
# {{- else }}
#     SERVER=mysql-{{ .Release.Name }}
# {{- end }}
#     OPTION=2
#     SOCKET=#
#     Driver=/usr/lib64/libmyodbc5w.so
