Vagrant::Project.configure(:virtualbox) do |env|
  test_react_mud_centos :test_react_mud_centos do

    provider{
      network{
        ip_address "10.6.7.100"
      }
      memory '480'
    }

  end
end
