load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:root][:chef][:berksfile])

cookbook_from_git 'chef_commons', '1.1.11'
cookbook_from_git 'extras', '0.1.61'
cookbook 'seven_zip', '~> 2.0.0'

cookbook 'build-essential'
cookbook 'ark', '5.0.0'
cookbook_from_git 'kube-config', '0.1.21'
cookbook_from_git 'helm', '0.1.32'
cookbook_from_git 'docker', '0.1.31'
cookbook_from_git 'nodejs', '0.1.22'

