load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:root][:chef][:berksfile])

cookbook_from_git 'chef_commons', '1.1.22'
cookbook_from_git 'extras', '0.1.61'
cookbook 'seven_zip', '~> 2.0.0'

cookbook 'build-essential'
cookbook 'ark', '5.0.0'
cookbook_from_git 'kube-config', '0.1.24'
cookbook_from_git 'docker', '0.1.39'
cookbook_from_github 'mstr-ecosystem-cookbooks', 'nodejs','16.19.0'
