name             'workspace'
maintainer       'DevOps'
maintainer_email 'DevOps@microstrategy.com'
description      'Installs/Configures workspace'
long_description 'Installs and configures a workspace for this project'
version          '1.0.0'

depends 'chef_commons'
depends 'extras'
depends 'kube-config'
depends 'helm'
depends 'docker'
depends 'nodejs'
