name             'TKN-.-snake_case_project_name-.-TKN'
maintainer       'Someone'
maintainer_email 'someone@microstrategy.com'
description      'Installs/Configures TKN-.-snake_case_project_name-.-TKN servers'
long_description 'Installs and configures the servers this project produces'
version          '1.0.0'