apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Release.Name }}
{{- include "namespace" . | indent 2 }}
data:
  odbc.ini: |-
    [ODBC Data Sources]
    poc_metadata=MySQL ODBC 5.x Driver
    tutorial-wh=MySQL ODBC 5.x Driver

    [ODBC]
    Trace=0
    TraceFile=odbctrace.out
    TraceDll=/opt/mstr/MicroStrategy/install/lib/MYtrcXX.so
    InstallDir=/iserver-install/BIN/Linux/odbc
    IANAAppCodePage=106
    UseCursorLib=0
    UNICODE=UTF-8

    [poc_metadata]
    DriverUnicodeType=1
    Description=MySQL ODBC 5.x Driver
    PORT=3306
    DATABASE={{ .Values.iserver.odbc.db_md_name }}
    CHARSET=utf8
    SERVER=mysql-md-{{ .Release.Name }}
    OPTION=2
    SOCKET=#
    Driver=/usr/lib64/libmyodbc5w.so

    [tutorial-wh]
    DriverUnicodeType=1
    Description=MySQL ODBC 5.x Driver
    PORT=3306
    DATABASE={{ .Values.iserver.odbc.db_wh_name }}
    CHARSET=utf8
    SERVER=mysql-wh-{{ .Release.Name }}
    OPTION=2
    SOCKET=#
    Driver=/usr/lib64/libmyodbc5w.so

  config.ini: |-
    [Server]
    Server=1
    Action=4
    InstanceName=CICD
    ProjectsToRegister=Consolidated Education Project\Hierarchies Project\Human Resources Analysis Module\MicroStrategy Tutorial\Relationships Project\Star\
    ProjectsToUnregister=
    DSName=poc_metadata
    DSNUser=root
    DSNPwd=mstr1234
    MDPrefix=
    DSSUser=Administrator
    DSSPwd=
    Port=34952
    EncryptPassword=0
    RegisterAsService=0
    StartServerAfterConfig=0
    ConfigureSSL=0
    SSLPort=
    CertificatePath=
    KeyPath=
    KeyPassword=
    DefaultStatisticsRep=0
    DefaultDSNNameDefaultStatistics=
    UserNameDefaultStatistics=
    UserPwdDefaultStatistics=
    EncryptUserPwdDefaultStatistics=
    DefaultStatisticsPrefix=
    kafkaHost(s)=
    ConfigMessagingService=0
    KeepStatisticsSettings=0
    RESTPort=34962

  configOverride.properties: |-
    iserver.default.hostname=iserver-{{ .Release.Name }}
    iserver.default.port={{ .Values.iserver.service.port }}
    auth.modes.available=1,16
    iserver.tlsEnabled = false
    iserver.maxPoolSize = 100
    session.searchWorkingSet = 3
    iserver.initialPoolSize = 10
    session.workingSet = 10
    iserver.requestTimeout = 120000
    services.collaboration.enabled = false
    services.collaboration.tlsEnabled = false
    identityToken.secretKey=tDiLgBAWoqERnkCLngcG