const EDITOR_PREFIX = 'HOME_SCREEN_CONFIG_EDITOR'
const MAIN_VIEW_PREFIX = 'HOME_SCREEN_CONFIG_MAIN'

export const LOAD_CONFIG_LIST_SUCCESS = `${MAIN_VIEW_PREFIX}_LOAD_CONFIG_LIST_SUCCESS`
export const LOAD_CONTENT_BUNDLE_LIST_SUCCESS = `${MAIN_VIEW_PREFIX}_LOAD_CONTENT_BUNDLE_LIST_SUCCESS`

/* ------------------------------ Current Config State ---------------------------- */

export const SET_CURRENT_CONFIG = `${EDITOR_PREFIX}_SET_CURRENT_CONFIG`
export const UPDATE_GENERAL_SETTINGS = `${EDITOR_PREFIX}_UPDATE_GENERAL_SETTINGS`
