export const colorGuideHexVals = [
    { name: 'Rose ###', color: '#FBDAD9' },
    { name: 'Peach ###', color: '#FFDEC6' },
    { name: 'Buttermilk ###', color: '#FFF3B3' },
    { name: 'Honeydew ###', color: '#E1F5C9' },
    { name: 'Mint ###', color: '#D7F6F0' },
    { name: 'Iceberg ###', color: '#DCECF1' },
    { name: 'Fog ###', color: '#DEDDFF' },
    { name: 'Lavender ###', color: '#DDCAFF' },
    { name: 'Pink ###', color: '#FDA29A' },
    { name: 'Coral ###', color: '#FFAE8B' },
    { name: 'Sweet Corn ###', color: '#FAD47F' },
    { name: 'Green Pea ###', color: '#BFE2A2' },
    { name: 'Aqua ###', color: '#AADED7' },
    { name: 'Frost ###', color: '#A6CCDD' },
    { name: 'Pale Purple ###', color: '#9D9FE0' },
    { name: 'Orchid ###', color: '#B496DD' },
    { name: 'Salmon ###', color: '#DB6657' },
    { name: 'Orange ###', color: '#D76322' },
    { name: 'Honey ###', color: '#E69912' },
    { name: 'Grass ###', color: '#83C962' },
    { name: 'Turquoise ###', color: '#55BFC3' },
    { name: 'Ocean Blue ###', color: '#1C8DD4' },
    { name: 'Royal Blue ###', color: '#4F60D6' },
    { name: 'Violet ###', color: '#834FBD' },
    { name: 'Ruby Red ###', color: '#C1292F' },
    { name: 'Rust ###', color: '#9A3A0A' },
    { name: 'Caramel ###', color: '#B27B11' },
    { name: 'Emerald ###', color: '#38AE6F' },
    { name: 'Teal ###', color: '#028F94' },
    { name: 'Indigo ###', color: '#0F6095' },
    { name: 'Sapphire ###', color: '#31329D' },
    { name: 'Plum ###', color: '#5C388C' },
    { name: 'Maroon ###', color: '#7E0F16' },
    { name: 'Chestnut ###', color: '#733413' },
    { name: 'Nutmeg ###', color: '#7B5B31' },
    { name: 'Forest ###', color: '#1D6F31' },
    { name: 'Pine Green ###', color: '#156962' },
    { name: 'Navy ###', color: '#193B67' },
    { name: 'Midnight ###', color: '#1B1575' },
    { name: 'Deep Purple ###', color: '#3A2471' },
    { name: 'Black ###', color: '#000000' },
    { name: 'Charcoal ###', color: '#35383A' },
    { name: 'Dark Gray ###', color: '#6C6C6C' },
    { name: 'Silver ###', color: '#ABABAB' },
    { name: 'Porcelain ###', color: '#DEDEDE' },
    { name: 'Mist ###', color: '#EBEBEB' },
    { name: 'Smoke White ###', color: '#F4F4F4' },
    { name: 'White ###', color: '#FFFFFF' },
];